base_params:
  master_seed: 2025
  experiment_type: "RECON_VECTORS"

evaluation:
  type: "emb_retrieval"
  # embedding_model: "local:all-mpnet-base-v2" # Not used for vector recon, but kept for consistency if needed by loader

data_config:
  name: "np_files"
  path: "local/wild_videos_embs/"
  limit: 100

recon_strategy:
  - type: "mean_closest"
  - type: "repeat_closest"

IMPORT masking_configs: masking_fill.yaml

