base_params:
  master_seed: 0x5EED

data_config:
  name: "wildQA"
  path: "datasets/wildQA/dev.json"
  limit: 103
  duration_limit: 61
  out_path: "datasets/wildQA/captions/"

llm:
  model_name: "gemini-2.5-pro"
  system_instructions: null
  temperature: 0.8
  thought_budget: -1
  response_schema: "list[CaptionedInterval]"
  prompt_template: "prompts/yt_video_processing/one_minute.txt"
  fps: 1
