base_params:
  master_seed: 0x5EED

data_config:
  name: "wildQA"
  path: "datasets/wildQA/dev_Agriculture.json"
  limit: null
  out_path: "datasets/wildQA/captions/"

llm:
  model_name: "gemini-2.5-pro"
  system_instructions: null
  temperature: 1.0
  thought_budget: -1
  response_schema: "list"
  prompt_template: "prompts/yt_video_processing/long.txt"
  fps: 1
