# =================================================================
# == Base Configuration
# == Holds common, stable parameters for all experiments.
# =================================================================

# --- Experiment Settings ---
experiment_name: "MaskedTranscriptReconstruction"
transcript_richness: "narrative_only" # Default richness level

# --- LLM Configuration ---
llm:
  model_name: "gemini-1.5-pro-latest" # Using the 'latest' tag is good practice
  temperature: 0.7
  max_output_tokens: 1024

# --- Data Source ---
# For now, we'll define our toy example directly in the code.
# This will later point to a file in the data/ directory.
data:
  source_type: "toy_example"

# --- Default Hyperparameters ---
# These can be overridden by specific experiment configs.
masking:
  scheme: "random"
  ratio: 0.5

random_seed: 42 # For reproducibility
