batch_name: "Baseline Reconstruction on Storytelling-100 (Controlled Masking)"

# Parameters that are constant for all runs in this batch
base_params:
  experiment_name: "MaskedCaptionsReconstruction"
  data:
    name: "video_storytelling"
    path: "./datasets/storytelling"
    limit: 100
  random_seed: 42
  strategy_configs: # Note: This is now a base_param since we are only testing one strategy
    - name: "baseline_repeat_last"
      type: "baseline_repeat_last"

# A list of masking configurations to iterate over
masking_configs:
  - scheme: "contiguous_controlled"
    # The runner will now iterate through this list
    mask_index: [0, 1, 2, 3, 4] 
    num_to_mask: 1
