base_params:
  master_seed: 2025

data_config:
  name: "video_storytelling"
  path: "datasets/storytelling/"
  limit: 100

recon_strategy:
  - name: "d_llm_zero_shot_v1.1"
    type: "llm"
    llm:
      model_name: "gemini-2.0-flash-001"
      temperature: 0.5
      prompt_template: "prompts/dense_zero_shot_v1.1.txt"

masking_configs:
  - scheme: "contiguous"
    seed: [11,22]
    width: [1,2,3,4,5,6,7]

