base_params:
  master_seed: 2025

data_config:
  name: "video_storytelling"
  path: "datasets/storytelling/"
  limit: 100

recon_strategy:
  - name: "llm_one_shot"
    type: "llm"
    llm:
      model_name: "gemini-2.0-flash-001"
      temperature: 0.5
      system_instructions: "prompts/sys_one_shot_v1.txt"
#  - name: "baseline_repeat_last"
#    type: "baseline_repeat_last"

masking_configs:
  - scheme: "contiguous"
    seed: [11,22]
    width: [1,2,3,4,5,6,7]

