# =================================================================
# == System Configuration
# == Defines machine-specific paths for data, caches, and results.
# =================================================================

paths:
  # The directory for MLflow to store its runs.
  # Use a file URI scheme for local paths.
  mlflow_tracking_uri: "file:./mlruns"

  # The directory for our embedding and function call cache.
  disk_cache: "disk_cache/"

  # The location of the input data source.
  datasets_root: "datasets/"

  # experiment logs
  log_dir: "logs"
