batch_name: "Toy Dataset with LLM"

# --- Parameters that are constant for all runs in this batch ---
base_params:
  experiment_name: "MaskedCaptionsReconstruction"
  master_seed: 42

data_config:
  name: "toy_data"
  path: "datasets/toy_dataset/data.json"

recon_strategy:
  - name: "baseline_repeat_last"
    type: "baseline_repeat_last"
  #- name: "llm_zero_shot_v1"
    #type: "llm"
    #llm:
      #model_name: "gemini-2.0-flash-exp"
      #temperature: 0.6
      #system_instructions: "prompts/sys_zero_shot_v1.txt"
  - name: "llm_zero_shot_v2"
    type: "llm"
    llm:
      model_name: "gemini-2.0-flash-001"
      temperature: 0.4
      system_instructions: "prompts/sys_one_shot_v1.txt"

# --- A list of masking rules to generate strategies from ---
masking_configs:
  - scheme: "contiguous"
    width: [2]
    seed: [1]
