base_params:
  master_seed: 2025
  experiment_type: "RECON_VECTORS"

evaluation:
  type: "emb_sim"

data_config:
  name: "wild_captions"
  path: "datasets/wildQA/captions__wild2/"
  limit: 100

recon_strategy:
  - type: "mean_closest"
  - type: "repeat_closest"


masking_configs:
  - scheme: "contiguous"
    seed: [11,22]
    width: [6,9,12,15,18,21,24,27,30,33,36,39,42,45]


