base_params:
  master_seed: 2025
  experiment_type: "recon"

evaluation:
  type: "emb_sim"

data_config:
  name: "wild_captions"
  path: "datasets/wildQA/captions__wild2/"
  limit: 100

recon_strategy:
  - name: "pro_d_zero_shot_v1.1__t=0.7"
    type: "llm"
    llm:
      model_name: "gemini-2.5-pro"
      thought_budget: -1
      temperature: 0.7
      prompt_template: "prompts/dense_zero_shot_v1.1.txt"
  - name: "baseline_repeat_last"
    type: "baseline_repeat_last"


masking_configs:
  - scheme: "contiguous"
    seed: [11,22]
    width: [6,9,12,15,18]

